INSERT INTO barbour_color_map (
    color_code,
    raw_name,
    norm_key,
    source,
    is_confirmed
)
VALUES
    ('BK', 'black', 'black', 'config_code_map', TRUE),
    ('NY', 'navy', 'navy', 'config_code_map', TRUE),
    ('OL', 'olive', 'olive', 'config_code_map', TRUE),
    ('WH', 'white', 'white', 'config_code_map', TRUE),
    ('GN', 'green', 'green', 'config_code_map', TRUE),
    ('GY', 'grey', 'grey', 'config_code_map', TRUE),
    ('BR', 'brown', 'brown', 'config_code_map', TRUE),
    ('BE', 'beige', 'beige', 'config_code_map', TRUE),
    ('SG', 'sage', 'sage', 'config_code_map', TRUE),
    ('ST', 'stone', 'stone', 'config_code_map', TRUE),
    ('BL', 'blue', 'blue', 'config_code_map', TRUE),
    ('PI', 'Arabesque', 'arabesque', 'config_code_map', TRUE),
    ('BR', 'Bark', 'bark', 'config_code_map', TRUE),
    ('SN', 'Beech/Classic', 'beech classic', 'config_code_map', TRUE),
    ('RE', 'Bordeaux', 'bordeaux', 'config_code_map', TRUE),
    ('ST', 'Clay', 'clay', 'config_code_map', TRUE),
    ('WH', 'Cloud', 'cloud', 'config_code_map', TRUE),
    ('GN', 'Forest', 'forest', 'config_code_map', TRUE),
    ('TN', 'Forest Mist', 'forest mist', 'config_code_map', TRUE),
    ('BE', 'Light Trench', 'light trench', 'config_code_map', TRUE),
    ('TN', 'Midnight', 'midnight', 'config_code_map', TRUE),
    ('BE', 'Mist', 'mist', 'config_code_map', TRUE),
    ('CR', 'Pearl', 'pearl', 'config_code_map', TRUE),
    ('BR', 'Black Oak', 'black oak', 'config_code_map', TRUE),
    ('OL', 'Fern', 'fern', 'config_code_map', TRUE),
    ('BR', 'Brown', 'brown', 'config_code_map', TRUE),
    ('GN', 'Dundee Tartan', 'dundee tartan', 'config_code_map', TRUE),
    ('BK', 'Black Carbon', 'black carbon', 'config_code_map', TRUE),
    ('BR', 'Umber', 'umber', 'config_code_map', TRUE),
    ('ST', 'Light Fawn', 'fawn light', 'config_code_map', TRUE),
    ('CR', 'Pearl/Navy', 'navy pearl', 'config_code_map', TRUE),
    ('BE', 'Trench', 'trench', 'config_code_map', TRUE),
    ('NY', 'Navy/Classic', 'classic navy', 'config_code_map', TRUE),
    ('OL', 'Deep Olive/Ancient Tartan', 'ancient deep olive tartan', 'config_code_map', TRUE),
    ('GN', 'Olive', 'olive', 'config_code_map', TRUE),
    ('BL', 'Sky Micro Check', 'check micro sky', 'config_code_map', TRUE),
    ('OL', 'Fern/Classic Tartan', 'classic fern tartan', 'config_code_map', TRUE),
    ('BR', 'Bark/Muted', 'bark muted', 'config_code_map', TRUE),
    ('OL', 'Tan/Dress Tartan', 'dress tan tartan', 'config_code_map', TRUE),
    ('NY', 'Royal Navy/Dress Tartan', 'dress navy royal tartan', 'config_code_map', TRUE),
    ('TA', 'Tan/Dress Tartan', 'dress tan tartan', 'config_code_map', TRUE),
    ('OL', 'Fern/Ancient Tartan', 'ancient fern tartan', 'config_code_map', TRUE),
    ('OL', 'Archive Olive/Ancient Tartan', 'ancient archive olive tartan', 'config_code_map', TRUE),
    ('RU', 'Rustic/Ancient Tartan', 'ancient rustic tartan', 'config_code_map', TRUE),
    ('OL', 'Fern/Beech/Ancient Tartan', 'ancient beech fern tartan', 'config_code_map', TRUE),
    ('OL', 'Fern/Sage/Ancient Tartan', 'ancient fern sage tartan', 'config_code_map', TRUE),
    ('RE', 'red', 'red', 'config_code_map', TRUE),
    ('PI', 'pink', 'pink', 'config_code_map', TRUE),
    ('CR', 'cream', 'cream', 'config_code_map', TRUE),
    ('CH', 'charcoal', 'charcoal', 'config_code_map', TRUE),
    ('TN', 'tan', 'tan', 'config_code_map', TRUE),
    ('KH', 'khaki', 'khaki', 'config_code_map', TRUE),
    ('YE', 'yellow', 'yellow', 'config_code_map', TRUE),
    ('OR', 'orange', 'orange', 'config_code_map', TRUE),
    ('PU', 'purple', 'purple', 'config_code_map', TRUE),
    ('IN', 'indigo', 'indigo', 'config_code_map', TRUE),
    ('TA', 'taupe', 'taupe', 'config_code_map', TRUE),
    ('CM', 'camel', 'camel', 'config_code_map', TRUE),
    ('TE', 'teal', 'teal', 'config_code_map', TRUE),
    ('CO', 'cobalt', 'cobalt', 'config_code_map', TRUE),
    ('AQ', 'aqua', 'aqua', 'config_code_map', TRUE),
    ('BU', 'burgundy', 'burgundy', 'config_code_map', TRUE),
    ('RU', 'rustic', 'rustic', 'config_code_map', TRUE),
    ('SN', 'sand', 'sand', 'config_code_map', TRUE),
    ('BC', 'black/charcoal', 'black charcoal', 'config_code_map', TRUE),
    ('HG', 'heather grey', 'grey heather', 'config_code_map', TRUE),
    ('ME', 'merlot', 'merlot', 'config_code_map', TRUE)
ON CONFLICT (color_code, raw_name) DO UPDATE
SET
    norm_key     = EXCLUDED.norm_key,
    source       = EXCLUDED.source,
    is_confirmed = EXCLUDED.is_confirmed;
