# -*- coding: utf-8 -*-
"""
自动从 barbour_products 导出，不要手工修改
格式保持与 BARBOUR_COLOR_CODE_MAP 完全一致
"""

BARBOUR_COLOR_CODE_MAP_GENERATED = {
    "AQ": {"en": "Lyons Blue", "zh": ""},
    "BC": {"en": "Trench/Tartan", "zh": ""},
    "BE": {"en": "Antique Bronze", "zh": ""},
    "BE": {"en": "Bark", "zh": ""},
    "BE": {"en": "Beige", "zh": ""},
    "BE": {"en": "Beige / Antique White", "zh": ""},
    "BE": {"en": "Beige/M Tart", "zh": ""},
    "BE": {"en": "Beige/Tartan", "zh": ""},
    "BE": {"en": "Birch / Gardenia", "zh": ""},
    "BE": {"en": "Black", "zh": ""},
    "BE": {"en": "Black/Tartan", "zh": ""},
    "BE": {"en": "Brindle", "zh": ""},
    "BE": {"en": "Brown Houndstooth", "zh": ""},
    "BE": {"en": "Brown/Ancient", "zh": ""},
    "BE": {"en": "Brown/Tartan", "zh": ""},
    "BE": {"en": "Camel", "zh": ""},
    "BE": {"en": "Chamoise", "zh": ""},
    "BE": {"en": "Chantilly", "zh": ""},
    "BE": {"en": "Dark Ecru", "zh": ""},
    "BE": {"en": "Ecru", "zh": ""},
    "BE": {"en": "Eggshell", "zh": ""},
    "BE": {"en": "Honey", "zh": ""},
    "BE": {"en": "Honey/Ancient", "zh": ""},
    "BE": {"en": "Honey/Ancient Poplar", "zh": ""},
    "BE": {"en": "Light Sand", "zh": ""},
    "BE": {"en": "Light Sandstone", "zh": ""},
    "BE": {"en": "Light Trench", "zh": ""},
    "BE": {"en": "Light Trench / Classic", "zh": ""},
    "BE": {"en": "Military Brown", "zh": ""},
    "BE": {"en": "Military Brown / Ancient Tartan", "zh": ""},
    "BE": {"en": "Military Brown / Hollyhock", "zh": ""},
    "BE": {"en": "Military Brown/Hessian Tartan", "zh": ""},
    "BE": {"en": "Military/Ancnt", "zh": ""},
    "BE": {"en": "Mink", "zh": ""},
    "BE": {"en": "Mist", "zh": ""},
    "BE": {"en": "Natural", "zh": ""},
    "BE": {"en": "Natural / Ecru", "zh": ""},
    "BE": {"en": "Neutral", "zh": ""},
    "BE": {"en": "New Mist", "zh": ""},
    "BE": {"en": "Oat", "zh": ""},
    "BE": {"en": "Oat / Black", "zh": ""},
    "BE": {"en": "Oat Stripe", "zh": ""},
    "BE": {"en": "Oatmeal", "zh": ""},
    "BE": {"en": "Oatmeal / Ancient Tartan", "zh": ""},
    "BE": {"en": "Olive", "zh": ""},
    "BE": {"en": "Pale Camel", "zh": ""},
    "BE": {"en": "Pale Camel / Hessian", "zh": ""},
    "BE": {"en": "Pearl", "zh": ""},
    "BE": {"en": "Pink/White 10", "zh": ""},
    "BE": {"en": "Safari Tartan", "zh": ""},
    "BE": {"en": "Stone", "zh": ""},
    "BE": {"en": "Taupe / Pearl", "zh": ""},
    "BE": {"en": "Taupe Suede", "zh": ""},
    "BE": {"en": "Timberwolf", "zh": ""},
    "BE": {"en": "Timberwolf / Marigold", "zh": ""},
    "BE": {"en": "Trench", "zh": ""},
    "BE": {"en": "Trench/Tartan", "zh": ""},
    "BE": {"en": "Washed Stone", "zh": ""},
    "BK": {"en": "Black", "zh": ""},
    "BK": {"en": "Black (Classic Tartan lining)", "zh": ""},
    "BK": {"en": "Black (Classic Tartan Lining)", "zh": ""},
    "BK": {"en": "Black / Ancient", "zh": ""},
    "BK": {"en": "Black / Black / Sage Tartan", "zh": ""},
    "BK": {"en": "Black / Cardinal", "zh": ""},
    "BK": {"en": "Black / Classic Tartan", "zh": ""},
    "BK": {"en": "Black / Dusky Khaki", "zh": ""},
    "BK": {"en": "Black / Grey", "zh": ""},
    "BK": {"en": "Black / Jasmine", "zh": ""},
    "BK": {"en": "Black / Light Blue", "zh": ""},
    "BK": {"en": "Black / Modern Tartan", "zh": ""},
    "BK": {"en": "Black / Oatmeal", "zh": ""},
    "BK": {"en": "Black / Onyx Tartan", "zh": ""},
    "BK": {"en": "Black / Pewter", "zh": ""},
    "BK": {"en": "Black / Pewter 2", "zh": ""},
    "BK": {"en": "Black / Safari Dress Tartan", "zh": ""},
    "BK": {"en": "Black / Scarlet Black Check", "zh": ""},
    "BK": {"en": "Black / Shadow", "zh": ""},
    "BK": {"en": "Black / Silver Birch", "zh": ""},
    "BK": {"en": "Black / Whisper White", "zh": ""},
    "BK": {"en": "Black / White", "zh": ""},
    "BK": {"en": "Black / Yellow", "zh": ""},
    "BK": {"en": "Black 2", "zh": ""},
    "BK": {"en": "Black Badge", "zh": ""},
    "BK": {"en": "Black Carbon", "zh": ""},
    "BK": {"en": "Black Classic", "zh": ""},
    "BK": {"en": "Black Marl", "zh": ""},
    "BK": {"en": "Black Mix", "zh": ""},
    "BK": {"en": "Black Modern", "zh": ""},
    "BK": {"en": "Black/Ancient", "zh": ""},
    "BK": {"en": "Black/Black", "zh": ""},
    "BK": {"en": "Black/C Tartan", "zh": ""},
    "BK": {"en": "Black/Camel", "zh": ""},
    "BK": {"en": "Black/Classic", "zh": ""},
    "BK": {"en": "Black/Classic Tartan", "zh": ""},
    "BK": {"en": "Black/Gardinia", "zh": ""},
    "BK": {"en": "Black/Grey", "zh": ""},
    "BK": {"en": "Black/Jasmine", "zh": ""},
    "BK": {"en": "Black/Jasmine L", "zh": ""},
    "BK": {"en": "Black/MCabernet", "zh": ""},
    "BK": {"en": "Black/Onyx Tartan", "zh": ""},
    "BK": {"en": "Black/Shadow", "zh": ""},
    "BK": {"en": "Black/Tartan", "zh": ""},
    "BK": {"en": "Black/White", "zh": ""},
    "BK": {"en": "Brown/Ancient", "zh": ""},
    "BK": {"en": "Classic black", "zh": ""},
    "BK": {"en": "Classic Black", "zh": ""},
    "BK": {"en": "Dusky Khaki", "zh": ""},
    "BK": {"en": "High Shine Black", "zh": ""},
    "BK": {"en": "Jasmine", "zh": ""},
    "BK": {"en": "Jasmine Leopard", "zh": ""},
    "BK": {"en": "Navy", "zh": ""},
    "BK": {"en": "New Black", "zh": ""},
    "BK": {"en": "Night Sky", "zh": ""},
    "BK": {"en": "Olive", "zh": ""},
    "BK": {"en": "Olive/An Tartan", "zh": ""},
    "BK": {"en": "Prince Of Wales", "zh": ""},
    "BK": {"en": "Sage", "zh": ""},
    "BK": {"en": "Sage/Fuchs/Anc", "zh": ""},
    "BK": {"en": "Sand", "zh": ""},
    "BK": {"en": "Silver Cloud", "zh": ""},
    "BK": {"en": "Snow Leopard", "zh": ""},
    "BK": {"en": "Snow Leopard Print", "zh": ""},
    "BK": {"en": "Unknown", "zh": ""},
    "BK": {"en": "Velvet Black", "zh": ""},
    "BK": {"en": "Washed Black", "zh": ""},
    "BL": {"en": "Arket Check", "zh": ""},
    "BL": {"en": "Arket Tartan", "zh": ""},
    "BL": {"en": "Atlantic Blue", "zh": ""},
    "BL": {"en": "Blue", "zh": ""},
    "BL": {"en": "Blue | Grey", "zh": ""},
    "BL": {"en": "Blue Denim", "zh": ""},
    "BL": {"en": "Blue Haze", "zh": ""},
    "BL": {"en": "Blue Stone", "zh": ""},
    "BL": {"en": "Bluefin", "zh": ""},
    "BL": {"en": "Bluestone", "zh": ""},
    "BL": {"en": "Breeze Blue", "zh": ""},
    "BL": {"en": "Camo", "zh": ""},
    "BL": {"en": "Chambray", "zh": ""},
    "BL": {"en": "Chambray (Shell Pink Logo)", "zh": ""},
    "BL": {"en": "China Blue", "zh": ""},
    "BL": {"en": "Cobalt Blue", "zh": ""},
    "BL": {"en": "Cool Blue", "zh": ""},
    "BL": {"en": "Dark Chambray", "zh": ""},
    "BL": {"en": "Dark Chambray Marl", "zh": ""},
    "BL": {"en": "Dark Denim", "zh": ""},
    "BL": {"en": "Dark Navy", "zh": ""},
    "BL": {"en": "Deep Blue", "zh": ""},
    "BL": {"en": "Denim", "zh": ""},
    "BL": {"en": "Heritage Blue", "zh": ""},
    "BL": {"en": "Ice Blue", "zh": ""},
    "BL": {"en": "Inky Blue", "zh": ""},
    "BL": {"en": "Light Blue Steel", "zh": ""},
    "BL": {"en": "Light Steel Blue", "zh": ""},
    "BL": {"en": "Navy", "zh": ""},
    "BL": {"en": "Neutral/Mandar", "zh": ""},
    "BL": {"en": "North Sea Blue", "zh": ""},
    "BL": {"en": "Pearl Blue", "zh": ""},
    "BL": {"en": "River Blue", "zh": ""},
    "BL": {"en": "Sky", "zh": ""},
    "BL": {"en": "Sky Micro Check", "zh": ""},
    "BL": {"en": "Stone Blue", "zh": ""},
    "BL": {"en": "Washed Blue", "zh": ""},
    "BL": {"en": "Washed Cobalt", "zh": ""},
    "BR": {"en": "Amaretto Check", "zh": ""},
    "BR": {"en": "Antique Bronze", "zh": ""},
    "BR": {"en": "Bark", "zh": ""},
    "BR": {"en": "Bark-Muted", "zh": ""},
    "BR": {"en": "Bark / Hessian Tartan", "zh": ""},
    "BR": {"en": "Bark/Classic", "zh": ""},
    "BR": {"en": "Bark/Muted", "zh": ""},
    "BR": {"en": "Black", "zh": ""},
    "BR": {"en": "Black Oak", "zh": ""},
    "BR": {"en": "Black Oak / Classic Tartan", "zh": ""},
    "BR": {"en": "Black Oak / Midnight", "zh": ""},
    "BR": {"en": "Brindle", "zh": ""},
    "BR": {"en": "Brown", "zh": ""},
    "BR": {"en": "Brown / Orange Check", "zh": ""},
    "BR": {"en": "Brown / Orange Check / Hessian Tartan", "zh": ""},
    "BR": {"en": "Brown/Classic", "zh": ""},
    "BR": {"en": "Brown/Tartan", "zh": ""},
    "BR": {"en": "Burnhill Brown Check", "zh": ""},
    "BR": {"en": "Chocolate", "zh": ""},
    "BR": {"en": "Classic Brown", "zh": ""},
    "BR": {"en": "Clay", "zh": ""},
    "BR": {"en": "Dark Brown", "zh": ""},
    "BR": {"en": "Dark Brown / Midnight", "zh": ""},
    "BR": {"en": "Dark Brown Club Check", "zh": ""},
    "BR": {"en": "Dark Brown/Midnight Oak", "zh": ""},
    "BR": {"en": "Dark Oak", "zh": ""},
    "BR": {"en": "Hessian / Navy Tartan", "zh": ""},
    "BR": {"en": "Java Red", "zh": ""},
    "BR": {"en": "Khaki Brown", "zh": ""},
    "BR": {"en": "Light Brown", "zh": ""},
    "BR": {"en": "Military Brown", "zh": ""},
    "BR": {"en": "Military Brown / Ancient Tartan", "zh": ""},
    "BR": {"en": "Mink", "zh": ""},
    "BR": {"en": "Oiled Brown Suede", "zh": ""},
    "BR": {"en": "Redwood", "zh": ""},
    "BR": {"en": "Rust", "zh": ""},
    "BR": {"en": "Rust Brown", "zh": ""},
    "BR": {"en": "Rustic Brown", "zh": ""},
    "BR": {"en": "Sage", "zh": ""},
    "BR": {"en": "Tan", "zh": ""},
    "BR": {"en": "Teak", "zh": ""},
    "BR": {"en": "Timberwolf", "zh": ""},
    "BR": {"en": "Transparent", "zh": ""},
    "BR": {"en": "Trench", "zh": ""},
    "BR": {"en": "Umber", "zh": ""},
    "BR": {"en": "Vicuna", "zh": ""},
    "BR": {"en": "Vicuna Gingham Check", "zh": ""},
    "BR": {"en": "Vicuna/Hessian", "zh": ""},
    "BR": {"en": "Vicuna/Tartan", "zh": ""},
    "BR": {"en": "White Pepper", "zh": ""},
    "BU": {"en": "Bluestone", "zh": ""},
    "BU": {"en": "Brook Blue", "zh": ""},
    "BU": {"en": "Concrete Blue", "zh": ""},
    "BU": {"en": "Dusty Blue", "zh": ""},
    "BU": {"en": "Ice Water", "zh": ""},
    "BU": {"en": "Inky Marl", "zh": ""},
    "BU": {"en": "Insignia Blue", "zh": ""},
    "BU": {"en": "Lead", "zh": ""},
    "BU": {"en": "Manor Blue", "zh": ""},
    "BU": {"en": "Midnight Blue", "zh": ""},
    "BU": {"en": "Ocean Sky", "zh": ""},
    "BU": {"en": "Pigment Navy", "zh": ""},
    "BU": {"en": "Rosette Blue", "zh": ""},
    "BU": {"en": "Royal Blue", "zh": ""},
    "BU": {"en": "Royal Blue Check", "zh": ""},
    "BU": {"en": "Sapphire Navy", "zh": ""},
    "BU": {"en": "Velvet Burgundy", "zh": ""},
    "CH": {"en": "Asphalt", "zh": ""},
    "CH": {"en": "Charcoal", "zh": ""},
    "CH": {"en": "Charcoal / Midnight", "zh": ""},
    "CH": {"en": "Charcoal Grey", "zh": ""},
    "CH": {"en": "Charcoal Marl", "zh": ""},
    "CH": {"en": "Charcoal Marl 2", "zh": ""},
    "CH": {"en": "Charcoal Mix", "zh": ""},
    "CH": {"en": "Dark Grey Marl", "zh": ""},
    "CH": {"en": "Dark Grey Marl / Classic", "zh": ""},
    "CM": {"en": "Camel", "zh": ""},
    "CM": {"en": "Camel / Hessian Tartan", "zh": ""},
    "CO": {"en": "Coral", "zh": ""},
    "CO": {"en": "Peach Nectar", "zh": ""},
    "CR": {"en": "Aran Tropical", "zh": ""},
    "CR": {"en": "Black", "zh": ""},
    "CR": {"en": "Blanc", "zh": ""},
    "CR": {"en": "Bone White", "zh": ""},
    "CR": {"en": "Calico", "zh": ""},
    "CR": {"en": "Cloud", "zh": ""},
    "CR": {"en": "Cream", "zh": ""},
    "CR": {"en": "Dove Grey", "zh": ""},
    "CR": {"en": "Ecru/Ancient", "zh": ""},
    "CR": {"en": "French Oak / Sky Dress Tartan", "zh": ""},
    "CR": {"en": "Gloss Silver Birch", "zh": ""},
    "CR": {"en": "Jasmine", "zh": ""},
    "CR": {"en": "Jasmine / Black", "zh": ""},
    "CR": {"en": "Jasmine / Burnished Gold", "zh": ""},
    "CR": {"en": "Jasmine / Dusky Khaki", "zh": ""},
    "CR": {"en": "Jasmine Leopard", "zh": ""},
    "CR": {"en": "Light Pearl", "zh": ""},
    "CR": {"en": "Light Pearl / Pale", "zh": ""},
    "CR": {"en": "Light Pearl / Safari Tartan", "zh": ""},
    "CR": {"en": "Neutral", "zh": ""},
    "CR": {"en": "Neutral/Mandar", "zh": ""},
    "CR": {"en": "Oak/ Tartan", "zh": ""},
    "CR": {"en": "Oatmeal / Silver Cloud", "zh": ""},
    "CR": {"en": "Oatmeal/Ancient Tartan", "zh": ""},
    "CR": {"en": "Parchment (Apricot Crush Logo)", "zh": ""},
    "CR": {"en": "Pearl", "zh": ""},
    "CR": {"en": "Pearl/Classic", "zh": ""},
    "CR": {"en": "Salt", "zh": ""},
    "CR": {"en": "Silver Birch", "zh": ""},
    "CR": {"en": "Silver Birch / Moss", "zh": ""},
    "CR": {"en": "Summer Pearl", "zh": ""},
    "CR": {"en": "Winter Pearl", "zh": ""},
    "GN": {"en": "Agave Green", "zh": ""},
    "GN": {"en": "Arabesque", "zh": ""},
    "GN": {"en": "Arabesque / Brown", "zh": ""},
    "GN": {"en": "Army Green", "zh": ""},
    "GN": {"en": "Bayleaf", "zh": ""},
    "GN": {"en": "Black", "zh": ""},
    "GN": {"en": "British Khaki", "zh": ""},
    "GN": {"en": "Cyberlime", "zh": ""},
    "GN": {"en": "Dark Green", "zh": ""},
    "GN": {"en": "Dark Moss", "zh": ""},
    "GN": {"en": "Dark Seaweed", "zh": ""},
    "GN": {"en": "Duffle Green", "zh": ""},
    "GN": {"en": "Dundee Tartan", "zh": ""},
    "GN": {"en": "Dundee Tartan/Ancient", "zh": ""},
    "GN": {"en": "Dusky Green", "zh": ""},
    "GN": {"en": "Dusky Green / Ancient Tartan", "zh": ""},
    "GN": {"en": "Dusky Green / Limeade", "zh": ""},
    "GN": {"en": "Dusky Green / Rosemary Tartan", "zh": ""},
    "GN": {"en": "Dusky Khaki", "zh": ""},
    "GN": {"en": "Dusky Khaki / Jasmine", "zh": ""},
    "GN": {"en": "Dusty Khaki", "zh": ""},
    "GN": {"en": "Empire Green", "zh": ""},
    "GN": {"en": "Envy", "zh": ""},
    "GN": {"en": "Evergreen", "zh": ""},
    "GN": {"en": "Fern", "zh": ""},
    "GN": {"en": "Fern Leaf/Sage", "zh": ""},
    "GN": {"en": "Fern Leaf/Sage/Light Sage", "zh": ""},
    "GN": {"en": "Fern Leaf/Sage/Natural", "zh": ""},
    "GN": {"en": "Fern/Green Heart", "zh": ""},
    "GN": {"en": "Fern/Green Heart Print", "zh": ""},
    "GN": {"en": "Forest", "zh": ""},
    "GN": {"en": "Forest River", "zh": ""},
    "GN": {"en": "Granite Green", "zh": ""},
    "GN": {"en": "Green", "zh": ""},
    "GN": {"en": "Green Slate", "zh": ""},
    "GN": {"en": "Green Smoke", "zh": ""},
    "GN": {"en": "Ivy Green", "zh": ""},
    "GN": {"en": "Jasmine Leopard", "zh": ""},
    "GN": {"en": "Kelly Green", "zh": ""},
    "GN": {"en": "Khaki", "zh": ""},
    "GN": {"en": "Light Moss", "zh": ""},
    "GN": {"en": "Light Sand/An", "zh": ""},
    "GN": {"en": "Limeade", "zh": ""},
    "GN": {"en": "Limeade / Light Sand", "zh": ""},
    "GN": {"en": "Mallard Green", "zh": ""},
    "GN": {"en": "Miltary Olive", "zh": ""},
    "GN": {"en": "Moss/Sand/ Pink", "zh": ""},
    "GN": {"en": "Navy", "zh": ""},
    "GN": {"en": "New Seaweed", "zh": ""},
    "GN": {"en": "Olive", "zh": ""},
    "GN": {"en": "Olive / Ancient Tartan", "zh": ""},
    "GN": {"en": "Olive / Classic Tartan", "zh": ""},
    "GN": {"en": "Pale Apple", "zh": ""},
    "GN": {"en": "Palm Leaf", "zh": ""},
    "GN": {"en": "Pigment Green/Breen", "zh": ""},
    "GN": {"en": "Pine Green", "zh": ""},
    "GN": {"en": "Pineapple/Green Heart Print", "zh": ""},
    "GN": {"en": "Racing Green", "zh": ""},
    "GN": {"en": "Rainy Day", "zh": ""},
    "GN": {"en": "Rifle Green", "zh": ""},
    "GN": {"en": "Royal Pineapple", "zh": ""},
    "GN": {"en": "Royal Pineapple Print", "zh": ""},
    "GN": {"en": "Sage", "zh": ""},
    "GN": {"en": "Seaweed", "zh": ""},
    "GN": {"en": "Seaweed Mix", "zh": ""},
    "GN": {"en": "Seaweed Sal", "zh": ""},
    "GN": {"en": "Shaded Emerald", "zh": ""},
    "GN": {"en": "Silv Birch/Moss", "zh": ""},
    "GN": {"en": "Thyme", "zh": ""},
    "GN": {"en": "Trailing Floral", "zh": ""},
    "GN": {"en": "Uniform Green", "zh": ""},
    "GN": {"en": "Unknown", "zh": ""},
    "GN": {"en": "Willow Green", "zh": ""},
    "GY": {"en": "Anthracite", "zh": ""},
    "GY": {"en": "Anthracite Marl", "zh": ""},
    "GY": {"en": "Asphalt", "zh": ""},
    "GY": {"en": "Asphalt Marl", "zh": ""},
    "GY": {"en": "Birch", "zh": ""},
    "GY": {"en": "Birch Multi", "zh": ""},
    "GY": {"en": "Charcoal", "zh": ""},
    "GY": {"en": "Chrome", "zh": ""},
    "GY": {"en": "Classic Grey", "zh": ""},
    "GY": {"en": "Clay", "zh": ""},
    "GY": {"en": "Concrete", "zh": ""},
    "GY": {"en": "Dark Grey", "zh": ""},
    "GY": {"en": "Dark Slate", "zh": ""},
    "GY": {"en": "Dark Slate/Ancient", "zh": ""},
    "GY": {"en": "Fog", "zh": ""},
    "GY": {"en": "Glacier Grey", "zh": ""},
    "GY": {"en": "Glacier Grey / Antique Bronze", "zh": ""},
    "GY": {"en": "Grey", "zh": ""},
    "GY": {"en": "Grey / Dress", "zh": ""},
    "GY": {"en": "Grey Marl", "zh": ""},
    "GY": {"en": "Grey Marl / Hessian", "zh": ""},
    "GY": {"en": "Grey/Dress", "zh": ""},
    "GY": {"en": "Grey/Tartan Tbc", "zh": ""},
    "GY": {"en": "Iron", "zh": ""},
    "GY": {"en": "Light Grey", "zh": ""},
    "GY": {"en": "Light Grey-Cabernet", "zh": ""},
    "GY": {"en": "Light Grey Marl", "zh": ""},
    "GY": {"en": "Light Grey Marl / Onyx Tartan", "zh": ""},
    "GY": {"en": "Light Grey Mélange", "zh": ""},
    "GY": {"en": "Limestone Grey", "zh": ""},
    "GY": {"en": "Mid Grey", "zh": ""},
    "GY": {"en": "Mid Grey - Loden", "zh": ""},
    "GY": {"en": "Mid Grey Marl", "zh": ""},
    "GY": {"en": "Mineral Grey", "zh": ""},
    "GY": {"en": "Mist", "zh": ""},
    "GY": {"en": "Mist Marl", "zh": ""},
    "GY": {"en": "Monochrome Tartan", "zh": ""},
    "GY": {"en": "Navy", "zh": ""},
    "GY": {"en": "New Charcoal", "zh": ""},
    "GY": {"en": "Oyster Grey", "zh": ""},
    "GY": {"en": "Pale Slate", "zh": ""},
    "GY": {"en": "Putty", "zh": ""},
    "GY": {"en": "Silver", "zh": ""},
    "GY": {"en": "Silver Birch", "zh": ""},
    "GY": {"en": "Silver Cl/Black", "zh": ""},
    "GY": {"en": "Silver Cloud", "zh": ""},
    "GY": {"en": "Slate Marl", "zh": ""},
    "GY": {"en": "Soft Grey Check / Onyx Tartan", "zh": ""},
    "GY": {"en": "Storm Grey", "zh": ""},
    "GY": {"en": "Tarmac", "zh": ""},
    "GY": {"en": "Ultimate Grey", "zh": ""},
    "GY": {"en": "Ultimate Grey / Shadow", "zh": ""},
    "GY": {"en": "Ultimate Grey/Shadow", "zh": ""},
    "HG": {"en": "Honey/Cabernet", "zh": ""},
    "IN": {"en": "Dark Denim", "zh": ""},
    "IN": {"en": "Dark Indigo", "zh": ""},
    "IN": {"en": "Dark Indigo / Safari Tartan", "zh": ""},
    "IN": {"en": "Hybrid Aero Denim", "zh": ""},
    "IN": {"en": "Indigo", "zh": ""},
    "IN": {"en": "Indigo/Tartan", "zh": ""},
    "IN": {"en": "Inky Blue", "zh": ""},
    "IN": {"en": "Raw", "zh": ""},
    "IN": {"en": "Rinse Wash", "zh": ""},
    "IN": {"en": "Vintage", "zh": ""},
    "IN": {"en": "Washed Indigo", "zh": ""},
    "KH": {"en": "British Khaki", "zh": ""},
    "KH": {"en": "Derby Tweed", "zh": ""},
    "KH": {"en": "Dusky Khaki", "zh": ""},
    "KH": {"en": "Golden Khaki", "zh": ""},
    "KH": {"en": "Green Slate", "zh": ""},
    "KH": {"en": "Khaki", "zh": ""},
    "KH": {"en": "Washed Khaki", "zh": ""},
    "ME": {"en": "High Shine Silver", "zh": ""},
    "MI": {"en": "Gun Metal", "zh": ""},
    "MI": {"en": "Light Gold", "zh": ""},
    "MI": {"en": "Medium Gold", "zh": ""},
    "MI": {"en": "Multi", "zh": ""},
    "MI": {"en": "Multi Check", "zh": ""},
    "MI": {"en": "Multi Stripe", "zh": ""},
    "MI": {"en": "Pineapple Print", "zh": ""},
    "MI": {"en": "Pink Tartan", "zh": ""},
    "MI": {"en": "Tropical Print", "zh": ""},
    "NY": {"en": "Black", "zh": ""},
    "NY": {"en": "Black Watch", "zh": ""},
    "NY": {"en": "Black Watch Tartan", "zh": ""},
    "NY": {"en": "Black/Gardinia", "zh": ""},
    "NY": {"en": "Brown/Tartan", "zh": ""},
    "NY": {"en": "Champion Blue", "zh": ""},
    "NY": {"en": "Classic Navy", "zh": ""},
    "NY": {"en": "Dark Denim", "zh": ""},
    "NY": {"en": "Dark Navy", "zh": ""},
    "NY": {"en": "Dark Navy / Ancient", "zh": ""},
    "NY": {"en": "Dark Navy / Ancient Tartan", "zh": ""},
    "NY": {"en": "Dark Navy / Blackwatch", "zh": ""},
    "NY": {"en": "Dark Navy / Hessian", "zh": ""},
    "NY": {"en": "Dark Navy / Hessian Tartan", "zh": ""},
    "NY": {"en": "Dark Navy / Midnight", "zh": ""},
    "NY": {"en": "Dark Navy / Sky Dress Tartan", "zh": ""},
    "NY": {"en": "Dark Navy Stripe", "zh": ""},
    "NY": {"en": "Dark Navy/Ancient Poplar", "zh": ""},
    "NY": {"en": "Dark Navy/Black/Dress Tartan", "zh": ""},
    "NY": {"en": "Dark Navy/Dress Tartan", "zh": ""},
    "NY": {"en": "Dark Worn", "zh": ""},
    "NY": {"en": "Deep Navy", "zh": ""},
    "NY": {"en": "Deep Navy / Classic Tartan", "zh": ""},
    "NY": {"en": "Deep Navy / Dress Tartan", "zh": ""},
    "NY": {"en": "Deep Navy/Classic", "zh": ""},
    "NY": {"en": "Dk Navy/Oak", "zh": ""},
    "NY": {"en": "Dusky Green", "zh": ""},
    "NY": {"en": "Green Loch", "zh": ""},
    "NY": {"en": "Green SMU", "zh": ""},
    "NY": {"en": "Honey/Ancient", "zh": ""},
    "NY": {"en": "International Navy", "zh": ""},
    "NY": {"en": "Lght Stone", "zh": ""},
    "NY": {"en": "Navy", "zh": ""},
    "NY": {"en": "Navy-White (SS24)", "zh": ""},
    "NY": {"en": "Navy-White (SS25)", "zh": ""},
    "NY": {"en": "Navy (Midnight Lining)", "zh": ""},
    "NY": {"en": "Navy (White Logo)", "zh": ""},
    "NY": {"en": "Navy / Bleached Pine Tartan", "zh": ""},
    "NY": {"en": "Navy / Blue Granite", "zh": ""},
    "NY": {"en": "Navy / Bright Green", "zh": ""},
    "NY": {"en": "Navy / Classic", "zh": ""},
    "NY": {"en": "Navy / Dress Tartan", "zh": ""},
    "NY": {"en": "Navy / Glo Chartr", "zh": ""},
    "NY": {"en": "Navy / Grey Marl", "zh": ""},
    "NY": {"en": "Navy / Hessian", "zh": ""},
    "NY": {"en": "Navy / Hessian Tartan", "zh": ""},
    "NY": {"en": "Navy / Midnight Oak", "zh": ""},
    "NY": {"en": "Navy / Northshore Tartan", "zh": ""},
    "NY": {"en": "Navy / Red / Stone", "zh": ""},
    "NY": {"en": "Navy / Sky Dress Tartan", "zh": ""},
    "NY": {"en": "Navy | Olive", "zh": ""},
    "NY": {"en": "Navy 2", "zh": ""},
    "NY": {"en": "Navy Dress", "zh": ""},
    "NY": {"en": "Navy Marl", "zh": ""},
    "NY": {"en": "Navy Marl 2", "zh": ""},
    "NY": {"en": "Navy Mix", "zh": ""},
    "NY": {"en": "Navy Pinstripe", "zh": ""},
    "NY": {"en": "Navy SKU: LLI0001NY91", "zh": ""},
    "NY": {"en": "Navy Stripe", "zh": ""},
    "NY": {"en": "Navy Windowpane", "zh": ""},
    "NY": {"en": "Navy Winter Dress Tartan", "zh": ""},
    "NY": {"en": "Navy/Brwn/Sand", "zh": ""},
    "NY": {"en": "Navy/Classic", "zh": ""},
    "NY": {"en": "Navy/Cloud", "zh": ""},
    "NY": {"en": "Navy/Ice", "zh": ""},
    "NY": {"en": "Navy/Sand Gingh", "zh": ""},
    "NY": {"en": "Navy/Tartan", "zh": ""},
    "NY": {"en": "New Navy", "zh": ""},
    "NY": {"en": "Night Sky", "zh": ""},
    "NY": {"en": "Olive", "zh": ""},
    "NY": {"en": "Olive (Copy)", "zh": ""},
    "NY": {"en": "Pink/White 10", "zh": ""},
    "NY": {"en": "Royal Navy", "zh": ""},
    "NY": {"en": "Royal Navy / Ancient Tartan", "zh": ""},
    "NY": {"en": "Royal Navy / Black / Dress Tartan", "zh": ""},
    "NY": {"en": "Royal Navy / Heritage Check", "zh": ""},
    "NY": {"en": "Royal Navy/Black/Dress Tartan", "zh": ""},
    "NY": {"en": "Royal Navy/Dress Tartan", "zh": ""},
    "NY": {"en": "Sage", "zh": ""},
    "NY": {"en": "Sapphire Navy", "zh": ""},
    "NY": {"en": "Sodalite Blue", "zh": ""},
    "NY": {"en": "Stone", "zh": ""},
    "NY": {"en": "Thyme", "zh": ""},
    "NY": {"en": "Unknown", "zh": ""},
    "NY": {"en": "Washed Cobalt", "zh": ""},
    "NY": {"en": "Washed Navy", "zh": ""},
    "NY": {"en": "Whisper White", "zh": ""},
    "Ol": {"en": "Olive", "zh": ""},
    "OL": {"en": "Archive Olive", "zh": ""},
    "OL": {"en": "Archive Olive / Ancient", "zh": ""},
    "OL": {"en": "Archive Olive / Beech / Ancient Tartan", "zh": ""},
    "OL": {"en": "Archive Olive/Beech/Ancient Tartan", "zh": ""},
    "OL": {"en": "Archive Olive/Olive/Beech", "zh": ""},
    "OL": {"en": "Beech", "zh": ""},
    "OL": {"en": "Black", "zh": ""},
    "OL": {"en": "Black/C Tartan", "zh": ""},
    "OL": {"en": "Black/Classic", "zh": ""},
    "OL": {"en": "Bleached olive", "zh": ""},
    "OL": {"en": "Bleached Olive", "zh": ""},
    "OL": {"en": "Brown", "zh": ""},
    "OL": {"en": "Brown/Tartan", "zh": ""},
    "OL": {"en": "Burnt Olive", "zh": ""},
    "OL": {"en": "Canvas Olive", "zh": ""},
    "OL": {"en": "Classic Tartan", "zh": ""},
    "OL": {"en": "Classic/Beacon", "zh": ""},
    "OL": {"en": "Clay", "zh": ""},
    "OL": {"en": "Dark Moss / Ancient Tartan", "zh": ""},
    "OL": {"en": "Dark Olive", "zh": ""},
    "OL": {"en": "Dark Olive SKU: LLI0001OL91", "zh": ""},
    "OL": {"en": "Deep Olive", "zh": ""},
    "OL": {"en": "Deep Olive / Sky Dress Tartan", "zh": ""},
    "OL": {"en": "Dusty Green", "zh": ""},
    "OL": {"en": "Ecru/Ancient", "zh": ""},
    "OL": {"en": "Envy", "zh": ""},
    "OL": {"en": "Envy Green", "zh": ""},
    "OL": {"en": "Fern", "zh": ""},
    "OL": {"en": "Fern / Ancient Tartan", "zh": ""},
    "OL": {"en": "Fern / Beech / Ancient Tartan", "zh": ""},
    "OL": {"en": "Fern / Classic Tartan", "zh": ""},
    "OL": {"en": "Fern / Sage / Ancient Tartan", "zh": ""},
    "OL": {"en": "Fern / Sage / Duffle Bag / Ancient Tartan", "zh": ""},
    "OL": {"en": "Fern/Ancient", "zh": ""},
    "OL": {"en": "Forest", "zh": ""},
    "OL": {"en": "Gardenia Tweed", "zh": ""},
    "OL": {"en": "Golden Olive / Ancient Tartan", "zh": ""},
    "OL": {"en": "Golden Olive/Ancient Tartan", "zh": ""},
    "OL": {"en": "Golden Olive/Olive/Ancient Tartan", "zh": ""},
    "OL": {"en": "Green", "zh": ""},
    "OL": {"en": "Kelp", "zh": ""},
    "OL": {"en": "Khaki Brown", "zh": ""},
    "OL": {"en": "Khaki Print", "zh": ""},
    "OL": {"en": "Light Sage", "zh": ""},
    "OL": {"en": "Mid Olive", "zh": ""},
    "OL": {"en": "Military Marl", "zh": ""},
    "OL": {"en": "Military Olive", "zh": ""},
    "OL": {"en": "Military Olive / Concrete Blue / Black", "zh": ""},
    "OL": {"en": "Navy", "zh": ""},
    "OL": {"en": "Navy/Classic", "zh": ""},
    "OL": {"en": "New Brown", "zh": ""},
    "OL": {"en": "New Olive", "zh": ""},
    "OL": {"en": "Olive", "zh": ""},
    "OL": {"en": "Olive-Classic", "zh": ""},
    "OL": {"en": "Olive (Purple | Yellow)", "zh": ""},
    "OL": {"en": "Olive / Ancient Tartan", "zh": ""},
    "OL": {"en": "Olive / Black", "zh": ""},
    "OL": {"en": "Olive / Blue / Red", "zh": ""},
    "OL": {"en": "Olive / Brown", "zh": ""},
    "OL": {"en": "Olive / Classic Tartan", "zh": ""},
    "OL": {"en": "Olive / Dark Brown", "zh": ""},
    "OL": {"en": "Olive / Dark Moss / Ancient Tartan", "zh": ""},
    "OL": {"en": "Olive / Gold", "zh": ""},
    "OL": {"en": "Olive / Hessian Tartan", "zh": ""},
    "OL": {"en": "Olive / Light Moss", "zh": ""},
    "OL": {"en": "Olive Check", "zh": ""},
    "OL": {"en": "Olive Check/Bl", "zh": ""},
    "OL": {"en": "Olive Ink", "zh": ""},
    "OL": {"en": "Olive Marl", "zh": ""},
    "OL": {"en": "Olive Mélange", "zh": ""},
    "OL": {"en": "Olive Mix", "zh": ""},
    "OL": {"en": "Olive Multi", "zh": ""},
    "OL": {"en": "Olive Multi Patchwork", "zh": ""},
    "OL": {"en": "Olive Twill", "zh": ""},
    "OL": {"en": "Olive/An Tartan", "zh": ""},
    "OL": {"en": "Olive/Ancient", "zh": ""},
    "OL": {"en": "Olive/Black", "zh": ""},
    "OL": {"en": "Olive/Classic", "zh": ""},
    "OL": {"en": "Olive/Khaki", "zh": ""},
    "OL": {"en": "Pink/White 10", "zh": ""},
    "OL": {"en": "Sage", "zh": ""},
    "OL": {"en": "Sage / Ancient Tartan", "zh": ""},
    "OL": {"en": "Sage / Zeni Pink", "zh": ""},
    "OL": {"en": "Sage/Ancient", "zh": ""},
    "OL": {"en": "Sage/Fuchs/Anc", "zh": ""},
    "OL": {"en": "Uniform Green", "zh": ""},
    "OL": {"en": "Uniform Green / Blue", "zh": ""},
    "OL": {"en": "Unknown", "zh": ""},
    "OL": {"en": "Washed Olive", "zh": ""},
    "OL": {"en": "Winter Moss", "zh": ""},
    "OL": {"en": "Winter Moss / Classic Tartan", "zh": ""},
    "OL": {"en": "Wintermoss", "zh": ""},
    "OR": {"en": "Bracken", "zh": ""},
    "OR": {"en": "Burnt Orange", "zh": ""},
    "OR": {"en": "Burnt Orange / Hessian", "zh": ""},
    "OR": {"en": "Burnt Orange Stripe", "zh": ""},
    "OR": {"en": "Copper", "zh": ""},
    "OR": {"en": "Dark Copper", "zh": ""},
    "OR": {"en": "Dark Ginger", "zh": ""},
    "OR": {"en": "Flame Orange", "zh": ""},
    "OR": {"en": "Light Peach", "zh": ""},
    "OR": {"en": "Orange", "zh": ""},
    "OR": {"en": "Peach Melba", "zh": ""},
    "OR": {"en": "Peach Parfait", "zh": ""},
    "OR": {"en": "Tan", "zh": ""},
    "PI": {"en": "Arabesque", "zh": ""},
    "PI": {"en": "Arabesque / Classic", "zh": ""},
    "PI": {"en": "Berry", "zh": ""},
    "PI": {"en": "Black", "zh": ""},
    "PI": {"en": "Cherry Blossom", "zh": ""},
    "PI": {"en": "Cherry Blossom Stripe", "zh": ""},
    "PI": {"en": "Classic Pink", "zh": ""},
    "PI": {"en": "Crystal Pink / Moss", "zh": ""},
    "PI": {"en": "Dusk Pink", "zh": ""},
    "PI": {"en": "Dusty Rose", "zh": ""},
    "PI": {"en": "Earth Pink", "zh": ""},
    "PI": {"en": "Gardenia", "zh": ""},
    "PI": {"en": "Gardenia Tartan", "zh": ""},
    "PI": {"en": "Granite Pink", "zh": ""},
    "PI": {"en": "Grey Marl", "zh": ""},
    "PI": {"en": "Mahogany Rose", "zh": ""},
    "PI": {"en": "Midnight Blue", "zh": ""},
    "PI": {"en": "Orchid", "zh": ""},
    "PI": {"en": "Pale Mauve", "zh": ""},
    "PI": {"en": "Pink", "zh": ""},
    "PI": {"en": "Pink Blush", "zh": ""},
    "PI": {"en": "Pink Clay", "zh": ""},
    "PI": {"en": "Pink Tartan", "zh": ""},
    "PI": {"en": "Pink Tartan/Beige Heart Print", "zh": ""},
    "PI": {"en": "Pink/White 10", "zh": ""},
    "PI": {"en": "Primrose Pink", "zh": ""},
    "PI": {"en": "Primrose Pink (SS25)", "zh": ""},
    "PI": {"en": "Quartz Pink", "zh": ""},
    "PI": {"en": "Raspberry", "zh": ""},
    "PI": {"en": "Raspberry / Jasmine", "zh": ""},
    "PI": {"en": "Raspberry/Jasmine", "zh": ""},
    "PI": {"en": "Rose Dust", "zh": ""},
    "PI": {"en": "Rose Quartz", "zh": ""},
    "PI": {"en": "Tea Rose", "zh": ""},
    "PI": {"en": "True Pink", "zh": ""},
    "PI": {"en": "Vintage Pink", "zh": ""},
    "PI": {"en": "Washed Raspberry", "zh": ""},
    "PU": {"en": "Aubergine / Pollen", "zh": ""},
    "PU": {"en": "Black Cherry", "zh": ""},
    "PU": {"en": "Black Cherry / Dark Brown / Muted Tartan", "zh": ""},
    "PU": {"en": "Bordeaux", "zh": ""},
    "PU": {"en": "Burnt Heather", "zh": ""},
    "PU": {"en": "Elderberry", "zh": ""},
    "PU": {"en": "Fig", "zh": ""},
    "PU": {"en": "Grape", "zh": ""},
    "PU": {"en": "Grey Lilac", "zh": ""},
    "PU": {"en": "Huckleberry", "zh": ""},
    "PU": {"en": "Navy", "zh": ""},
    "PU": {"en": "Pale Mauve", "zh": ""},
    "PU": {"en": "Plum Grey", "zh": ""},
    "PU": {"en": "Potent Merlot", "zh": ""},
    "PU": {"en": "Thistle", "zh": ""},
    "RE": {"en": "Antique Red", "zh": ""},
    "RE": {"en": "Biking Red", "zh": ""},
    "RE": {"en": "Black", "zh": ""},
    "RE": {"en": "Black Cherry", "zh": ""},
    "RE": {"en": "Black Cherry / Dark Brown / Muted Tartan", "zh": ""},
    "RE": {"en": "Bordeaux", "zh": ""},
    "RE": {"en": "Brick Red", "zh": ""},
    "RE": {"en": "Burnt Heather", "zh": ""},
    "RE": {"en": "Burnt Henna", "zh": ""},
    "RE": {"en": "Burnt Henna Stripe", "zh": ""},
    "RE": {"en": "Cranberry", "zh": ""},
    "RE": {"en": "Dark Rust", "zh": ""},
    "RE": {"en": "Fired Brick", "zh": ""},
    "RE": {"en": "Highland Red", "zh": ""},
    "RE": {"en": "Java Red", "zh": ""},
    "RE": {"en": "Mahogony", "zh": ""},
    "RE": {"en": "Merlot", "zh": ""},
    "RE": {"en": "Merlot / Muted Tartan", "zh": ""},
    "RE": {"en": "Merlot / Rustic / Beech / Muted Tartan", "zh": ""},
    "RE": {"en": "Port", "zh": ""},
    "RE": {"en": "Red", "zh": ""},
    "RE": {"en": "Red / Grey", "zh": ""},
    "RE": {"en": "Red Tartan", "zh": ""},
    "RE": {"en": "Red Velvet", "zh": ""},
    "RE": {"en": "Rosa", "zh": ""},
    "RE": {"en": "Rosette Red", "zh": ""},
    "RE": {"en": "Ruby", "zh": ""},
    "RE": {"en": "Ruby Marl", "zh": ""},
    "RE": {"en": "Rust", "zh": ""},
    "RE": {"en": "Scarlet", "zh": ""},
    "RE": {"en": "Windsor", "zh": ""},
    "RE": {"en": "Wine", "zh": ""},
    "RE": {"en": "Winter Red", "zh": ""},
    "RU": {"en": "Rustic", "zh": ""},
    "RU": {"en": "Rustic / Classic", "zh": ""},
    "RU": {"en": "Rustic / Muted Tartan", "zh": ""},
    "RU": {"en": "Rustic Brown", "zh": ""},
    "RU": {"en": "Rustic/Muted Tartan", "zh": ""},
    "RU": {"en": "Sage", "zh": ""},
    "SG": {"en": "Black", "zh": ""},
    "SG": {"en": "Black / Sage Check", "zh": ""},
    "SG": {"en": "Empire Green", "zh": ""},
    "SG": {"en": "Forest", "zh": ""},
    "SG": {"en": "Light Sage", "zh": ""},
    "SG": {"en": "Oatmeal/Ancient", "zh": ""},
    "SG": {"en": "Olive", "zh": ""},
    "SG": {"en": "Olive / Sage", "zh": ""},
    "SG": {"en": "Rosin", "zh": ""},
    "SG": {"en": "Sage", "zh": ""},
    "SG": {"en": "Sage / Ancient Poplar Tartan", "zh": ""},
    "SG": {"en": "Sage / Ancient Tartan", "zh": ""},
    "SG": {"en": "Sage / Classic", "zh": ""},
    "SG": {"en": "Sage / Greenloch Tartan", "zh": ""},
    "SG": {"en": "Sage / Rustic / Ancient Tartan", "zh": ""},
    "SG": {"en": "Sage / Shadow", "zh": ""},
    "SG": {"en": "Sage / White", "zh": ""},
    "SG": {"en": "Sage Houndstooth / Sand Dune", "zh": ""},
    "SG": {"en": "Sage Houndstooth/Mist", "zh": ""},
    "SG": {"en": "Sage Multi", "zh": ""},
    "SG": {"en": "Sage/Ancient", "zh": ""},
    "SG": {"en": "Sage/Classic", "zh": ""},
    "SG": {"en": "Sage/Shadow", "zh": ""},
    "SG": {"en": "SG51", "zh": ""},
    "SG": {"en": "Thyme", "zh": ""},
    "SN": {"en": "Beech", "zh": ""},
    "SN": {"en": "Beech / Ancient Tartan", "zh": ""},
    "SN": {"en": "Beech / Classic", "zh": ""},
    "SN": {"en": "Bronze", "zh": ""},
    "SN": {"en": "Bronze Brown", "zh": ""},
    "SN": {"en": "Cumin", "zh": ""},
    "SN": {"en": "D Green/Tartan", "zh": ""},
    "SN": {"en": "Dark Sand", "zh": ""},
    "SN": {"en": "Light Sand", "zh": ""},
    "SN": {"en": "Light Sand / Ancient Tartan", "zh": ""},
    "SN": {"en": "Light Sand / Black", "zh": ""},
    "SN": {"en": "Light Sand / Bran", "zh": ""},
    "SN": {"en": "Light Sand / Rosemary Tartan", "zh": ""},
    "SN": {"en": "Light Sand / Safari Tartan", "zh": ""},
    "SN": {"en": "Light Sand/An", "zh": ""},
    "SN": {"en": "Light Sand/Drss", "zh": ""},
    "SN": {"en": "Light Trench", "zh": ""},
    "SN": {"en": "Sand", "zh": ""},
    "SN": {"en": "Sand / Ancient", "zh": ""},
    "SN": {"en": "Sand / Archive Olive / Beech", "zh": ""},
    "SN": {"en": "Sand Dune", "zh": ""},
    "SN": {"en": "Sandstone", "zh": ""},
    "SN": {"en": "Tan", "zh": ""},
    "SN": {"en": "Tan-Black", "zh": ""},
    "ST": {"en": "Black", "zh": ""},
    "ST": {"en": "Brindle", "zh": ""},
    "ST": {"en": "Brindle Check", "zh": ""},
    "ST": {"en": "Clay", "zh": ""},
    "ST": {"en": "Concrete", "zh": ""},
    "ST": {"en": "Concrete / Northshore Tartan", "zh": ""},
    "ST": {"en": "Dark Brindle", "zh": ""},
    "ST": {"en": "Dark Denim", "zh": ""},
    "ST": {"en": "Dark Stone", "zh": ""},
    "ST": {"en": "Envy", "zh": ""},
    "ST": {"en": "Fossil", "zh": ""},
    "ST": {"en": "Light Fawn", "zh": ""},
    "ST": {"en": "Light Stone", "zh": ""},
    "ST": {"en": "Light Trench", "zh": ""},
    "ST": {"en": "Mist", "zh": ""},
    "ST": {"en": "Mist / Dress Tartan", "zh": ""},
    "ST": {"en": "Mist / Hessian Tartan", "zh": ""},
    "ST": {"en": "Mist/Hessian", "zh": ""},
    "ST": {"en": "Natural/Camel/Black", "zh": ""},
    "ST": {"en": "Navy", "zh": ""},
    "ST": {"en": "New Oatmeal", "zh": ""},
    "ST": {"en": "New Sand", "zh": ""},
    "ST": {"en": "New Stone", "zh": ""},
    "ST": {"en": "No Data", "zh": ""},
    "ST": {"en": "Oat", "zh": ""},
    "ST": {"en": "Oat / Cherry Blossom", "zh": ""},
    "ST": {"en": "Oat Multi", "zh": ""},
    "ST": {"en": "Oatmeal", "zh": ""},
    "ST": {"en": "Oatmeal Stripe", "zh": ""},
    "ST": {"en": "Oatmeal/Tartan", "zh": ""},
    "ST": {"en": "Pearl", "zh": ""},
    "ST": {"en": "Pebble", "zh": ""},
    "ST": {"en": "Rainy Day", "zh": ""},
    "ST": {"en": "Sand Dune / Classic", "zh": ""},
    "ST": {"en": "Shaded Mustard", "zh": ""},
    "ST": {"en": "Stone", "zh": ""},
    "ST": {"en": "Stone / Ancient Tartan", "zh": ""},
    "ST": {"en": "Stone / Navy Check", "zh": ""},
    "ST": {"en": "Stone Marl", "zh": ""},
    "ST": {"en": "Stone/Navy", "zh": ""},
    "ST": {"en": "Washed Stone", "zh": ""},
    "ST": {"en": "Washed Stone / Bleached Pine", "zh": ""},
    "TA": {"en": "Barbour Tartan (Assortment 2)", "zh": ""},
    "TA": {"en": "Cedar", "zh": ""},
    "TA": {"en": "Dark Tan", "zh": ""},
    "TA": {"en": "Fox Suede", "zh": ""},
    "TA": {"en": "Tan", "zh": ""},
    "TA": {"en": "Timber Tan", "zh": ""},
    "TE": {"en": "Vintage Teal", "zh": ""},
    "TE": {"en": "Vintage Teal / Dress Tartan", "zh": ""},
    "TN": {"en": "Ancient", "zh": ""},
    "TN": {"en": "Autumn Dress", "zh": ""},
    "TN": {"en": "Black Slate", "zh": ""},
    "TN": {"en": "Black Slate Tartan", "zh": ""},
    "TN": {"en": "Classic", "zh": ""},
    "TN": {"en": "Classic Tartan", "zh": ""},
    "TN": {"en": "Dress", "zh": ""},
    "TN": {"en": "Fernwood Tartan", "zh": ""},
    "TN": {"en": "Glenmor Olive Tartan", "zh": ""},
    "TN": {"en": "Midnight Oak", "zh": ""},
    "TN": {"en": "Midnight Oak Tartan", "zh": ""},
    "TN": {"en": "Mixed Tartan", "zh": ""},
    "TN": {"en": "Modern", "zh": ""},
    "TN": {"en": "Recycled Classic Tartan", "zh": ""},
    "TN": {"en": "Saltmarsh", "zh": ""},
    "TN": {"en": "Saltmarsh Tartan", "zh": ""},
    "TN": {"en": "Tan", "zh": ""},
    "TN": {"en": "Winterberry Tartan", "zh": ""},
    "WH": {"en": "Aran Tropical", "zh": ""},
    "WH": {"en": "Birch", "zh": ""},
    "WH": {"en": "Black / White", "zh": ""},
    "WH": {"en": "Calico White", "zh": ""},
    "WH": {"en": "Classic White", "zh": ""},
    "WH": {"en": "Cloud", "zh": ""},
    "WH": {"en": "Cloud - Spiced Pumpkin Check", "zh": ""},
    "WH": {"en": "Cloud / Black Stripe", "zh": ""},
    "WH": {"en": "Cloud / Blue Haze", "zh": ""},
    "WH": {"en": "Cloud / Hessian", "zh": ""},
    "WH": {"en": "Cloud / Kelly Green", "zh": ""},
    "WH": {"en": "Cloud / Navy", "zh": ""},
    "WH": {"en": "Cloud/Navy", "zh": ""},
    "WH": {"en": "Dark Navy", "zh": ""},
    "WH": {"en": "Ecru", "zh": ""},
    "WH": {"en": "Ecru / Oatmeal", "zh": ""},
    "WH": {"en": "Ecru Stripe", "zh": ""},
    "WH": {"en": "Linen White / Ancient Tartan", "zh": ""},
    "WH": {"en": "Neutral", "zh": ""},
    "WH": {"en": "New Cloud", "zh": ""},
    "WH": {"en": "New Ecru", "zh": ""},
    "WH": {"en": "New White", "zh": ""},
    "WH": {"en": "Off White", "zh": ""},
    "WH": {"en": "Optic White", "zh": ""},
    "WH": {"en": "Tropical /Beige Heart Print", "zh": ""},
    "WH": {"en": "Whisper White", "zh": ""},
    "WH": {"en": "Whisper White / Blue", "zh": ""},
    "WH": {"en": "Whisper White / Brindle", "zh": ""},
    "WH": {"en": "Whisper White 2", "zh": ""},
    "WH": {"en": "White", "zh": ""},
    "WH": {"en": "White / Black", "zh": ""},
    "WH": {"en": "White Dress", "zh": ""},
    "YE": {"en": "Harvest Gold", "zh": ""},
    "YE": {"en": "Honey", "zh": ""},
    "YE": {"en": "Honey Gold", "zh": ""},
    "YE": {"en": "Light Honey", "zh": ""},
    "YE": {"en": "Seaweed Sal", "zh": ""},
    "YE": {"en": "Sunray Yellow", "zh": ""},
    "YE": {"en": "Yellow Haze", "zh": ""},
}
