-- ========== 删除旧表（注意顺序：先删依赖表） ==========
DROP TABLE IF EXISTS barbour_offers;
DROP TABLE IF EXISTS barbour_products;
DROP TABLE IF EXISTS barbour_inventory;
DROP TABLE IF EXISTS barbour_supplier_map;

-- ========== 创建新表 ==========
CREATE TABLE barbour_products (
    id SERIAL PRIMARY KEY,

    -- Barbour 核心 SKU（商品编码 + 尺码）
    product_code VARCHAR(50) NOT NULL,          -- Barbour 商品编码，如 MWX0339NY91
    size VARCHAR(20) NOT NULL,                -- 尺码，如 M / UK 10 / XL

    -- 基础属性
    style_name VARCHAR(255) NOT NULL,         -- 款式名，如 Ashby Wax Jacket
    color VARCHAR(100) NOT NULL,              -- 颜色，如 Navy
    gender VARCHAR(20),                       -- 性别：Men / Women / Kids
    category VARCHAR(100),                    -- 分类：Jacket / Coat / Shirt / Bag ...
    title VARCHAR(255),                       -- 标题（完整商品名，带品牌+款式+颜色）
    product_description TEXT,                 -- 商品描述（来自官网/站点）
    match_keywords TEXT[],                    -- 提取的关键词，用于匹配其他网站标题

    -- 数据来源追踪
    source_site VARCHAR(100),                 -- 来源站点（barbour / O&C / PMD / manual）
    source_url TEXT,                          -- 来源链接
    source_rank INT DEFAULT 999,              -- 来源优先级：0=barbour官网,1=有编码站点,2=人工补码,999=未知

    -- 时间戳
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- 唯一约束：每个 SKU 唯一（编码 + 尺码）
    UNIQUE(product_code, size)
);

-- ========== 自动更新时间戳触发器 ==========
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_barbour_products_updated ON barbour_products;
CREATE TRIGGER trg_barbour_products_updated
BEFORE UPDATE ON barbour_products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ========== 表 2：库存价格表 offers ==========
-- 1) 表结构（product_code 允许为空）
-- ================================
-- Barbour Offers 表（A 方案：生成列）
-- ================================

-- 1) 先删旧表（注意：CASCADE 会同时删掉依赖的索引/触发器/外键）
DROP TABLE IF EXISTS barbour_offers CASCADE;

CREATE TABLE barbour_offers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 唯一识别：站点 + 链接 + 尺码
  site_name     VARCHAR(100) NOT NULL,
  offer_url     TEXT         NOT NULL,
  size          VARCHAR(20)  NOT NULL,

  -- 商品编码（可空，后续可回填）
  product_code  VARCHAR(50),

  -- 价格与库存
  price_gbp            NUMERIC(10,2),          -- 当前售价（可能为空）
  original_price_gbp   NUMERIC(10,2),          -- 原价（RRP）
  stock_count          INT DEFAULT 0,          -- ✅ 只保留数字库存

  -- 维护字段
  is_active     BOOLEAN   DEFAULT TRUE,
  first_seen    TIMESTAMP DEFAULT NOW(),
  last_seen     TIMESTAMP DEFAULT NOW(),
  last_checked  TIMESTAMP DEFAULT NOW(),

  -- ============ 生成列 ============
  sale_price_gbp NUMERIC(10,2)
    GENERATED ALWAYS AS (COALESCE(price_gbp, original_price_gbp)) STORED,

  discount_pct NUMERIC(5,1)
    GENERATED ALWAYS AS (
      CASE
        WHEN original_price_gbp IS NOT NULL
         AND COALESCE(price_gbp, original_price_gbp) < original_price_gbp
        THEN ROUND( (1 - COALESCE(price_gbp, original_price_gbp) / NULLIF(original_price_gbp, 0)) * 100, 1)
        ELSE 0
      END
    ) STORED,

  -- 约束
  CONSTRAINT uq_barbour_offer UNIQUE (site_name, offer_url, size),
  CONSTRAINT chk_price_nonneg CHECK (
    (price_gbp IS NULL OR price_gbp >= 0)
    AND (original_price_gbp IS NULL OR original_price_gbp >= 0)
  )
);

-- 时间戳触发器：更新即刷新 last_seen / last_checked
CREATE OR REPLACE FUNCTION barbour_offers_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.last_seen := NOW();
  NEW.last_checked := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_barbour_offers_touch ON barbour_offers;
CREATE TRIGGER trg_barbour_offers_touch
BEFORE UPDATE ON barbour_offers
FOR EACH ROW
EXECUTE FUNCTION barbour_offers_touch();

-- 实用索引
CREATE INDEX IF NOT EXISTS idx_bo_product_code  ON barbour_offers(product_code);
CREATE INDEX IF NOT EXISTS idx_bo_is_active     ON barbour_offers(is_active);
CREATE INDEX IF NOT EXISTS idx_bo_site_discount ON barbour_offers(site_name, discount_pct DESC);
CREATE INDEX IF NOT EXISTS idx_bo_discount_desc ON barbour_offers(discount_pct DESC);
CREATE INDEX IF NOT EXISTS idx_bo_site_url      ON barbour_offers(site_name, offer_url);
CREATE INDEX IF NOT EXISTS idx_bo_last_checked  ON barbour_offers(last_checked);

-- 5)（可选）对历史数据进行一次“触发”式更新以刷新 last_seen
-- UPDATE barbour_offers SET product_code = product_code;


-- 可选索引



-- =========================
-- Barbour 发布表（与 clarks_jingya_inventory 对齐）
-- 仅新增 3 个选源字段：source_site / source_offer_url / source_price_gbp
-- =========================
DROP TABLE IF EXISTS barbour_inventory;

CREATE TABLE barbour_inventory (
    id SERIAL PRIMARY KEY,

    -- 基础信息（保持与 clarks_jingya_inventory 一致）
    product_code VARCHAR(200) NOT NULL,      -- 这里写 Barbour 的 color_code，如 MWX0339NY91
    product_url  TEXT NOT NULL,              -- 选源链接（或你保留历史链接）
    size         VARCHAR(10) NOT NULL,       -- 尺码（S/M/L/XL 或 UK/INT）
    gender       VARCHAR(10),                -- 男款/女款/童款（可留空）

    -- 商品补充字段
    product_description TEXT,
    product_title       TEXT,
    style_category      VARCHAR(20),

    -- 淘宝&渠道绑定（完全沿用字段名，便于你现有代码复用）
    channel_product_id  VARCHAR(50),
    channel_item_id     VARCHAR(50),
    item_id             VARCHAR(50),
    skuid               VARCHAR(50),
    sku_name            VARCHAR(200),

    -- 库存与价格（沿用）
    ean                  VARCHAR(50),
    stock_count          INTEGER DEFAULT 0,
    original_price_gbp   NUMERIC(10, 2),
    discount_price_gbp   NUMERIC(10, 2),
    jingya_price_rmb     NUMERIC(12,2),
    taobao_price_rmb     NUMERIC(12,2),

    -- 状态控制（沿用）
    last_checked TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_published BOOLEAN DEFAULT FALSE,

    -- 仅为 Barbour 多供应商新增的 3 个“选源”字段（最小增量）
    source_site        VARCHAR(100),         -- 选中的站点（如 O&C / Allweathers / PMD 等）
    source_offer_url   TEXT,                 -- 选源 URL（可与 product_url 同步）
    source_price_gbp   NUMERIC(10, 2),       -- 选源英镑价（你的折算脚本用 discount_price_gbp 也可）

    -- 唯一约束：同一商品+尺码唯一（与 clarks 保持一致）
    UNIQUE (product_code, size)
);

-- 实用索引（一次建好即可）
CREATE INDEX IF NOT EXISTS idx_barbour_inv_sku   ON barbour_inventory(product_code, size);
CREATE INDEX IF NOT EXISTS idx_barbour_inv_item  ON barbour_inventory(item_id);
CREATE INDEX IF NOT EXISTS idx_barbour_inv_skuid ON barbour_inventory(skuid);
CREATE INDEX IF NOT EXISTS idx_bo_code   ON barbour_offers(product_code);
CREATE INDEX IF NOT EXISTS idx_bo_active ON barbour_offers(is_active);



-- =========================
-- Barbour 发布表（与 supplier和鲸芽 的映射关系表）
-- =========================

CREATE TABLE IF NOT EXISTS barbour_supplier_map (
  product_code VARCHAR(50) PRIMARY KEY,
  site_name    VARCHAR(100) NOT NULL  -- 和 barbour_offers.site_name 对齐
);