COLOR_MAP = {
    "|amphora                              |": "|amphora",
    "|archive olive                        |": "|archive",
    "|archive olive/ancient black floral   |": "|archive",
    "|archive olive/ancient tartan         |": "|archive",
    "|archive olive/black/beech/ancient    |": "|archive",
    "|asphalt marl/white                   |": "|asphalt",
    "|bark                                 |": "|bark",
    "|bark/classic                         |": "|bark",
    "|bayleaf                              |": "|bayleaf",
    "|beech                                |": "|beech",
    "|beige                                |": "|beige",
    "|beige/antique white                  |": "|beige",
    "|beige/dress                          |": "|beige",
    "|beige/dress gordon                   |": "|beige",
    "|beige/muted tartan                   |": "|beige",
    "|beige/sky dress tartan               |": "|beige",
    "|black                                |": "|black",
    "|black carbon                         |": "|black",
    "|black/ancient                        |": "|black",
    "|black/ancient tartan                 |": "|black",
    "|black/black                          |": "|black",
    "|black/envy green                     |": "|black",
    "|black/gold                           |": "|black",
    "|black/light blue steel               |": "|black",
    "|black/pewter                         |": "|black",
    "|black/safari dress tartan            |": "|black",
    "|black/safari tartan                  |": "|black",
    "|blackclassic                         |": "|blackclassic",
    "|blackolive                           |": "|blackolive",
    "|blackpewter                          |": "|blackpewter",
    "|blackyellow                          |": "|blackyellow",
    "|blanc                                |": "|blanc",
    "|bleached olive                       |": "|bleached",
    "|blue stone                           |": "|blue",
    "|bluefin                              |": "|bluefin",
    "|bordeaux                             |": "|bordeaux",
    "|breen/ancient tartan                 |": "|breen",
    "|breen/dress tartan/dusky rose        |": "|breen",
    "|breen/dusky green/ancient tartan     |": "|breen",
    "|breeze blue                          |": "|breeze",
    "|burnt heather                        |": "|burnt",
    "|burnt olive                          |": "|burnt",
    "|calico                               |": "|calico",
    "|camel                                |": "|camel",
    "|chamoise                             |": "|chamoise",
    "|charcoal                             |": "|charcoal",
    "|charcoal/winter                      |": "|charcoal",
    "|chrome                               |": "|chrome",
    "|classic black                        |": "|classic",
    "|classic brown                        |": "|classic",
    "|classic green                        |": "|classic",
    "|classic navy                         |": "|classic",
    "|classic tartan                       |": "|classic",
    "|classic white                        |": "|classic",
    "|cloud                                |": "|cloud",
    "|color                                |": "|color",
    "|concrete                             |": "|concrete",
    "|concrete/northshore                  |": "|concrete",
    "|conrete                              |": "|conrete",
    "|coral                                |": "|coral",
    "|cumin                                |": "|cumin",
    "|cyrstal pink/moss                    |": "|cyrstal",
    "|dark denim                           |": "|dark",
    "|dark indigo/ safari dress tartan     |": "|dark",
    "|dark moss                            |": "|dark",
    "|dark moss/classic                    |": "|dark",
    "|dark navy                            |": "|dark",
    "|dark navy/ safari dress tartan       |": "|dark",
    "|dark navy/ancient tartan             |": "|dark",
    "|dark navy/dress gordon               |": "|dark",
    "|dark navy/modern                     |": "|dark",
    "|dark navy/rosemary tartan            |": "|dark",
    "|dark navy/sky dress tartan           |": "|dark",
    "|dark olive                           |": "|dark",
    "|dark petrol/river birch              |": "|dark",
    "|dark sand                            |": "|dark",
    "|dark slate                           |": "|dark",
    "|deep olive/ancient tartan            |": "|deep",
    "|deep olive/sky dress tartan          |": "|deep",
    "|deep pruce                           |": "|deep",
    "|deep pruce/gardenia                  |": "|deep",
    "|dirty khaki/safari dress tartan      |": "|dirty",
    "|dove grey                            |": "|dove",
    "|dufflebag/classic                    |": "|dufflebag",
    "|dusky green                          |": "|dusky",
    "|dusky green/ancient                  |": "|dusky",
    "|dusky green/breen/ancient tartan     |": "|dusky",
    "|dusky green/classic                  |": "|dusky",
    "|dusky green/rosemary tartan          |": "|dusky",
    "|dusty green                          |": "|dusty",
    "|empire green                         |": "|empire",
    "|envy                                 |": "|envy",
    "|envy green                           |": "|envy",
    "|envy green/light blue steel          |": "|envy",
    "|fern                                 |": "|fern",
    "|flame orange                         |": "|flame",
    "|forest river                         |": "|forest",
    "|fossil                               |": "|fossil",
    "|gloss silver birch                   |": "|gloss",
    "|golden khaki                         |": "|golden",
    "|granite green                        |": "|granite",
    "|green slate                          |": "|green",
    "|green/safari dress tartan            |": "|green",
    "|grey marl                            |": "|grey",
    "|gun metal                            |": "|gun",
    "|heritage blue                        |": "|heritage",
    "|high shine black                     |": "|high",
    "|high shine silver                    |": "|high",
    "|highland olive/sand                  |": "|highland",
    "|ice blue                             |": "|ice",
    "|ice blue/dark navy                   |": "|ice",
    "|ice water                            |": "|ice",
    "|indigo stripe                        |": "|indigo",
    "|international navy                   |": "|international",
    "|khaki brown/ancient tartan green rose|": "|khaki",
    "|leopard print/classic                |": "|leopard",
    "|light  sand/dress stewart            |": "|light",
    "|light blue steel                     |": "|light",
    "|light gold                           |": "|light",
    "|light moss                           |": "|light",
    "|light peach                          |": "|light",
    "|light pearl                          |": "|light",
    "|light pearl/pale pink                |": "|light",
    "|light pearl/safari dress tartan      |": "|light",
    "|light sage                           |": "|light",
    "|light sand                           |": "|light",
    "|light sand/ancient                   |": "|light",
    "|light sand/dress                     |": "|light",
    "|light sand/dusk                      |": "|light",
    "|light sand/rosemary tartan           |": "|light",
    "|light sand/safari dress tartan       |": "|light",
    "|light sand/safari tartan             |": "|light",
    "|light steel blue                     |": "|light",
    "|light steel blue/silver birch        |": "|light",
    "|light steel/silver birch             |": "|light",
    "|light stone                          |": "|light",
    "|light trench                         |": "|light",
    "|light trench/sky dress tartan        |": "|light",
    "|light trenchlight trench             |": "|light",
    "|limeade                              |": "|limeade",
    "|limeade/light sand                   |": "|limeade",
    "|major brown                          |": "|major",
    "|mandarin                             |": "|mandarin",
    "|mandarin orange                      |": "|mandarin",
    "|manor blue                           |": "|manor",
    "|medium gold                          |": "|medium",
    "|midnight blue                        |": "|midnight",
    "|military brown                       |": "|military",
    "|military brown/ancient               |": "|military",
    "|military brown/ancient tartan        |": "|military",
    "|military brown/dress                 |": "|military",
    "|military brown/sky dress tartan      |": "|military",
    "|military olive                       |": "|military",
    "|mineral grey                         |": "|mineral",
    "|mist                                 |": "|mist",
    "|mistdress                            |": "|mistdress",
    "|natural                              |": "|natural",
    "|navy                                 |": "|navy",
    "|navy pinstripe/hessian               |": "|navy",
    "|navy/blackwatch                      |": "|navy",
    "|navy/bleached pine                   |": "|navy",
    "|navy/dress                           |": "|navy",
    "|navy/northshore                      |": "|navy",
    "|navy/sky dress tartan                |": "|navy",
    "|navydress                            |": "|navydress",
    "|navypale pink                        |": "|navypale",
    "|navypearl                            |": "|navypearl",
    "|neutral                              |": "|neutral",
    "|neutral/neutral                      |": "|neutral",
    "|noah madras pink                     |": "|noah",
    "|north blue sea                       |": "|north",
    "|north sea blue                       |": "|north",
    "|oatmeal/ancient tartan               |": "|oatmeal",
    "|olive                                |": "|olive",
    "|olive check                          |": "|olive",
    "|olive/ancient tartan                 |": "|olive",
    "|oliveclassic                         |": "|oliveclassic",
    "|olivepale pink                       |": "|olivepale",
    "|oyster grey                          |": "|oyster",
    "|pale mauve                           |": "|pale",
    "|pale slate                           |": "|pale",
    "|peach parfait                        |": "|peach",
    "|pearl                                |": "|pearl",
    "|pearl jaguar                         |": "|pearl",
    "|pearlnavy                            |": "|pearlnavy",
    "|pearlstone                           |": "|pearlstone",
    "|pigment green/breen                  |": "|pigment",
    "|pigment navy                         |": "|pigment",
    "|pigment white                        |": "|pigment",
    "|primrose pink                        |": "|primrose",
    "|quartz pink                          |": "|quartz",
    "|redwood                              |": "|redwood",
    "|royal navy                           |": "|royal",
    "|royal navy/ancient tartan            |": "|royal",
    "|royal navy/heritage check            |": "|royal",
    "|rust brown                           |": "|rust",
    "|rust brown/sky dress tartan          |": "|rust",
    "|rustic                               |": "|rustic",
    "|rustic brown                         |": "|rustic",
    "|rustic/ancient tartan                |": "|rustic",
    "|safari dress tartan/mist             |": "|safari",
    "|sage                                 |": "|sage",
    "|sage/dress stewart                   |": "|sage",
    "|sagedress                            |": "|sagedress",
    "|salt                                 |": "|salt",
    "|sand                                 |": "|sand",
    "|sand/dress black floral              |": "|sand",
    "|sapphire navy                        |": "|sapphire",
    "|scarlet/dress tartan                 |": "|scarlet",
    "|seaweed salad/ancient                |": "|seaweed",
    "|seaweed salad/dress gordon           |": "|seaweed",
    "|silver birch                         |": "|silver",
    "|silver birch/silver birch            |": "|silver",
    "|silver cloud                         |": "|silver",
    "|sky dress tartan/dark navy           |": "|sky",
    "|sky micro check                      |": "|sky",
    "|stone                                |": "|stone",
    "|stone check                          |": "|stone",
    "|stone/ancient tartan                 |": "|stone",
    "|summer pearl                         |": "|summer",
    "|sun bleached yellow                  |": "|sun",
    "|tan                                  |": "|tan",
    "|tan/dress tartan                     |": "|tan",
    "|taupe                                |": "|taupe",
    "|taupepearl                           |": "|taupepearl",
    "|tayside teal/blackwatch              |": "|tayside",
    "|thistle                              |": "|thistle",
    "|timberwolf                           |": "|timberwolf",
    "|toast                                |": "|toast",
    "|tobacco                              |": "|tobacco",
    "|trailing floral                      |": "|trailing",
    "|transparent                          |": "|transparent",
    "|trench                               |": "|trench",
    "|uniform green                        |": "|uniform",
    "|uniform green/bleached pine          |": "|uniform",
    "|vintage pink                         |": "|vintage",
    "|vintage teal                         |": "|vintage",
    "|vintage teal/dress                   |": "|vintage",
    "|walnut/safari dress tartan           |": "|walnut",
    "|washed blue                          |": "|washed",
    "|washed cobalt                        |": "|washed",
    "|washed stone                         |": "|washed",
    "|washed stone/bleached pine           |": "|washed",
    "|whisper white                        |": "|whisper",
    "|white                                |": "|white",
    "|whiteblack                           |": "|whiteblack",
    "|yellow/blackwatch                    |": "|yellow",
}


def normalize_color(raw_color: str) -> str:
    color = raw_color.lower().strip().replace(" (uk)", "")
    if "/" in color:
        color = color.split("/")[0].strip()
    if color in COLOR_MAP:
        return COLOR_MAP[color]
    else:
        return color.split()[0]  # fallback
